spring:
  application:
    name: familier-api
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  security:
    user:
      name: ${APP_ADMIN_USER}
      password: ${APP_ADMIN_PASS}
server:
  port: ${CORE_SERVICE_PORT:8081}
debug: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      access-token-expiration: 3600000
      refresh-token-expiration: 604800000
    oauth2:
      google:
        client-id: ${PUBLIC_GOOGLE_CLIENT_ID}