version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: familier-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: familier
      MYSQL_USER: familier
      MYSQL_PASSWORD: familier123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
