spring:
  security:
    user:
      name: admin
      password: 123456
server:
  port: 8080
debug: true

application:
  security:
    jwt:
      secret-key: DayLaMotCaiSecretKeyRatDaiVaBaoMatDeTestHeThongCuaToi123456789
      access-token-expiration: 3600000
      refresh-token-expiration: 604800000
    oauth2:
      google:
        client-id: DayLaMotCaiSecretKeyRatDaiVaBaoMatDeTestHeThongCuaToi123456789.clientID