spring:
  cloud:
    gateway:
      routes:
        - id: ai_service_route
          uri: ${AI_SERVICE_URL}
          predicates:
            - Path=/ai/**
        - id: core_service_route
          uri: ${CORE_SERVICE_URL}
          predicates:
            - Path=/**

server:
  port: ${GATEWAY_PORT:8080}